language: ruby
rvm:
  - 2.3.1
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-lang-cjk texlive-fonts-recommended texlive-latex-extra dvipsk-ja gv ghostscript
script:
  - bundle exec rake pdf
