language: ruby
rvm:
  - 2.3.1
addons:
  apt:
    packages:
      - texlive-lang-cjk
      - texlive-lang-japanese
      - texlive-fonts-recommended
      - texlive-latex-extra
      - ghostscript
script:
  - bundle exec rake pdf
