language: ruby
rvm:
  - 2.3.1
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texlive-lang-cjk texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra latex-xcolor --no-install-recommends
  - npm install
script:
  - bundle exec rake all 0<&-
  - npm run build
after_success:
  - wget https://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz -O - | tar xzvf - kindlegen
  - ./kindlegen techbookfest.epub -c2 -verbose -o techbookfest.mobi
deploy:
  provider: releases
  api_key:
    secure: hf81/vRZ9uIXn+keK/haPr6QzEglarQiPtl2Bozq4cFe/DMWzS/R3NK6VDD4hhIksw1GVGl2p5T2JeL1Xe9DSbidQ10qwIkZPBwUSEFWQ6BrfrtllIA6cqoOgFnxVXcYDy5mML1BNHDovCM0EMIWMjgbveJKvwZEtOCP82porC94weJvqrAYYrT7zP5i1ci76RgVt3D/Mihi4zAEl+F2NB9+ku418zKCdzmdXNmw1oCyshgfW/NvgRUmfw4Y0hYCZ/zS7iwLIbsiVS25frLtrKk9kBV906NKYeOOGJpr7x90/gZzh+5rpaiZgELd1lnRmsUS8urwY/CU+ganheahOEdCBEGHYKc2yh7wKHs5n268+stqzl2xaWNJWD4JX1AFZwTk3yLPyiIZBhMHdLYvirlL/1ETdtFliYdY/t2bJyL3piYfJrsNp1IU2OQ3CmY5H/cS0dmLsRjmE4+H/f15A81FI9pgjggibqhb6D0AnxFxvhdZfFGxGu1/VWuwy1jfJIdgLzfsODt5l1VtYj4JbJ8+hmjJnB/URXbFPkPe1LQwm54aGUUizCj5MA9v5Jx/l0DQgJuwl8NgSAVKJw87hkv4eQjOeATYlG1CPSV/mvNLRIaQUMxjBgLD6YrjTlEI4ECAXP5MM8kEEjI7F51YZiz7r9tVOV9GuopJr3wXwgQ=
  file:
    - techbookfest.pdf
    - techbookfest.epub
    - techbookfest.mobi
  skip_cleanup: true
  on:
    repo: SunProIO/SunPro-techbookfest
    tags: true
notifications:
  slack:
    secure: M0ogd7WfwjXPnOYcOVBO8P11yEhfbD29fJxfdPAo+kuqtsMvi0UfPX2cXeolGd8dJTpCD5UJvzrzvOXcBtGNudBv7j3WNy+VYhiQT+QdH9XndNxlgr9szUcfUx0h9CRk7BtHbAoz0N2lS4+dvyzDni8F0EtkCS3TIOFYQMNbGm/QWffufEdDky2R19gAuGGEvPs16uvzLVH+kAjvL0mTfaWr98DjdyCh0Hsf7x604arN8FpgDXWPzpMjD6yWCFVwwtGPS7C2gzgZzfQlU+d7l7buuaNDA/h3D54EuMs5EmLWzCuqdi6YNoE2CREFYcNo7/ddZtii7BMhlQVj/m+X36Qe+23dbjod9UqW06Oz8bAEPEqTPLGt10L/XMZI6i1rrc454WexeE+jbKWJ39Bu6jEcnDipdMPHsc6SMRfqMUVpfr+16N3V1oJekBn5BFYZhwGj6DczmadRFUhIJkNApVcbUm53iDk5Bdh863KkeTnRCxqnuY0xn8NBTaUP1m2yv9TMmOvhUrQ3AZl8bLi54jIpTYpHtTaL+WxDfu1pWTp/YryOqsnjoru6GrQamVA7/dR+/Gw4XIUbdiYUZjkW9Bc9NpeDLkDnThVBMn+Yd++fE1D5rmlvN9p0pvwe+/3RCVvAGEGLFW0j61t/loaiQDA3IYx8oT20Vg2Gxy2zytY=
